name: Publication
on:
  push:
    branches:
      - main
jobs:
  publish-app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Set access token
        env:
          TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npm set //registry.npmjs.org/:_authToken $TOKEN
      - name: Publish
        run: npm publish --access public
  tag-repo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Store version
        run: echo "APP_VERSION=$(npm run --silent get-version)" >> $GITHUB_ENV
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ env.APP_VERSION }}",
              sha: context.sha
            })
