name: Publish application
on:
  push:
    branches:
      - main-test
jobs:
  publish-app:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Set access token
        env:
          TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npm set //registry.npmjs.org/:_authToken $TOKEN
      - name: Publish
        run: npm publish --access public
